version: "3"
services:
  db:
    build: ./mysql
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - nginx_default
  wordpress:
    depends_on:
      - db
    image: wordpress:5.3.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_NAME=ieice
    volumes:
      - wordpress:/var/www/html
    networks:
      - nginx_default

volumes:
  wordpress:
  dbdata:
networks:
  nginx_default:
    external: true
