version: "3.2"
services:
  udpserver:
    depends_on:
      - nbiot_mongodb
    build: ./udpserver
    container_name: udpserver
    restart: unless-stopped
    volumes: 
      - ./udpserver/csv:/app/csv
    networks:
      - nginx_default
      - nbiot_network
  nbiot_mongodb:
    image: mongo
    container_name: nbiot_mongodb
    restart: unless-stopped
    networks:
      - nbiot_network
    volumes:
      - nbiot-volume:/data/db
volumes:
  nbiot-volume:
networks:
  nbiot_network:
    driver: bridge
  nginx_default:
    external: true
